# Generated by Django 3.0.4 on 2020-12-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Django_Rest_Framework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetpostdrf',
            name='like',
        ),
        migrations.CreateModel(
            name='TweetLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('tweetPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_Rest_Framework.TweetPostDrf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweetpostdrf',
            name='likes',
            field=models.ManyToManyField(through='Django_Rest_Framework.TweetLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
