# Generated by Django 3.0.4 on 2020-12-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Rest_Framework', '0004_auto_20201202_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetlike',
            old_name='postLike',
            new_name='like',
        ),
    ]
