# Generated by Django 3.0.4 on 2020-12-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Rest_Framework', '0005_auto_20201202_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetlike',
            name='like',
        ),
    ]
