# Generated by Django 3.0.4 on 2020-12-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Something',
        ),
    ]
