# Generated by Django 3.0.4 on 2020-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhr_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetpost',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
