# Generated by Django 3.0.4 on 2020-11-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xhr_APP', '0003_auto_20201117_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetpost',
            options={'ordering': ['-id']},
        ),
    ]
